version: "3.5"

services:
  php_fpm:
      build: .
      container_name: grav_php_fpm
      restart: always
      working_dir: /usr/share/nginx/grav
      networks:
          - grav
      volumes:
          - ./:/usr/share/nginx/grav
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
        image: nginx:1.18
        container_name: grav_nginx
        restart: always
        working_dir: /usr/share/nginx/grav
        networks:
            - grav
        ports:
            - "80:80"
        volumes:
            - ./:/usr/share/nginx/grav
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

networks:
  grav:
    driver: bridge
